- hosts: all
  become: true
  tasks:
    - name: group add  
      group: 
        name: developer
        state: present
    - name: user add 
      user:
        name: harry
        state: present 
